---
- name: Install dependencies
  package:
    name: bcc
  become: yes

- name: Setup service
  copy:
    content: |
      [Unit]
      Description=BPF ci probe

      [Service]
      ExecStart=/bin/python3 -u {{ ansible_user_dir }}/src/softwarefactory-project.io/software-factory/ci-tracer/src/agent.py {{ ci_tracer_args|default('') }} --json --summary {{ ansible_user_dir }}/zuul-output/logs/ci-tracer-summary.json --output {{ ansible_user_dir }}/zuul-output/logs/ci-tracer.json

      [Install]
      WantedBy=default.target
    dest: /etc/systemd/system/ci-tracer.service
  become: yes

- name: Start service
  systemd:
    name: ci-tracer
    state: started
    daemon_reload: yes
  become: yes
